### ISSUE TITLE
Significant content inconsistencies between ch and en version of RTM RESTful API doc

### ISSUE THREAD

**Issue by yamasite** [AgoraDoc/en#3]
# Where is the problem?

https://github.com/AgoraDoc/cn/blob/master/Real-time-Messaging/restfulapi/rtm_restfulapi.yaml
https://github.com/AgoraDoc/en/blob/master/Real-time-Messaging/restfulapi/rtm_restfulapi.yaml

# What is the problem?

The following content exists in ch doc but not in en doc:

```yaml
 message_history_query_response:
      type: object
      properties:
        result:
          type: string
          description: 请求结果。
        offset:
          type: integer
          description: 当前时间段内的消息偏移量。
        limit:
          type: integer
          description: 单页历史消息条数。
        location:
          type: string
          description: 历史消息资源地址。你可以从这个 URL 调用 GET 方法 获取查询结果。
        
    message_history:
      type: object
      required:
        - filter
        - offset
        - limit
        - order
      properties:
        filter:
          type: object
          description: >-
            筛选条件

            <div class="info-msg">
              <i class="fa fa-info-circle"></i><sup>1</sup> source 和 destination 的匹配原则详见下表：
            </div>

              | `source` | `destination` | 说明                                          |
              | :------- | :------------ | :-------------------------------------------- |
              | null     | null          | `source` 和 `destination` 不得同时为空。        |
              | null     | UserA         | UserA 在指定时间内收到的所有消息。                |
              | null     | ChannelA      | ChannelA 在指定时间段内收到的所有频道消息。        |
              | UserA    | null          | UserA 在指定时间段内发送的所有消息。               |
              | channelA | 任意字符串      | 返回空值。                                     |
              | UserA    | UserB         | UserA 在指定时间段内发送给 UserB 的所有点对点消息。 |
              | UserA    | ChannelA      | UserA 在指定时间段内发送到 ChannelA 的所有频道消息。|

          properties:
            source:
              type: string
              description: （视情况）消息发送方。<sup>1</sup>
            destination:
              type: string  
              description: （视情况）消息接收方。<sup>1</sup>
            start_time:
              type: string
              description: （必选）历史消息查询起始时间。使用 [ISO8601](http://en.wikipedia.org/wiki/ISO_8601) 标准为 UTC 时间。
            end_time:
              type: string
              description: （必选）历史消息查询结束时间。使用 [ISO8601](http://en.wikipedia.org/wiki/ISO_8601) 标准为 UTC 时间。      
        offset:
          type: integer
          description: 当前时间段内的消息偏移量。
        limit:
          type: integer
          description: 单页历史消息条数。可选值：<ul><li>20</li><li>50</li><li>100</li></ul>  
        order:
          type: string
          description: （可选）排序方法 <ul><li> 按时间顺序（默认）： asc </li><li>按时间倒序： desc </li></ul>
    count:
      type: object
      properties:
        source:
          type: string
          description: （视情况）消息发送方。<sup>1</sup>
        destination:
          type: string  
          description: （视情况）消息接收方。<sup>1</sup>
        start_time:
          type: string
          description: （必选）历史消息查询起始时间。使用 [ISO8601](http://en.wikipedia.org/wiki/ISO_8601) 标准为 UTC 时间。
        end_time:
          type: string
          description: （必选）历史消息查询结束时间。使用 [ISO8601](http://en.wikipedia.org/wiki/ISO_8601) 标准为 UTC 时间。
    count_response:
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果
        code:
          type: string
          description: >-
            资源准备情况：

            - 资源准备完成： "ok"

            - 资源还未准备完成，请稍后重试： "in progress" <sup>2</sup>

            <div class="info-msg">
                <i class="fa fa-info-circle"></i><sup>2</sup> 当服务器返回 "in progress" 时，请间隔 2 秒再发起 count 请求。
            </div> 
        count:
          type: integer
          description: 历史消息数目。 
    get_response:
      type: object
      properties:
        result:
          type: string
          description: 本次请求结果
        code:
          type: string
          description: >-
            资源准备情况：

            - 资源准备完成： "ok"

            - 资源还未准备完成，请稍后重试： "in progress" <sup>2</sup>

            <div class="info-msg">
                <i class="fa fa-info-circle"></i><sup>2</sup> 当服务器返回 "in progress" 时，请间隔 2 秒再发起 count 请求。
            </div> 
        message:
          type: array
          items:
            type: object
            properties:
              src:
                type: string
                description: 消息发送方。
              dst:
                type: string
                description: 消息接收方。
              payload:
                type: string
                description: 消息体。当前版本仅支持文本消息。
              ts:
                type: string
                description: 服务器接收时间。使用 [ISO8601](http://en.wikipedia.org/wiki/ISO_8601) 标准为 UTC 时间。
```

```yaml
    handle:
      name: handle
      in: path
      required: true
      description: >-
        历史消息查询资源，可以从历史消息 `query` 方法的响应包体的 `location` 字段获取。
      schema:
        type: string
```
